// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHQViTDrXUVnJ70dTM7DlU9MVwvI2XjXE',
    appId: '1:602524351324:web:3522d3317c0cb7e16bdf99',
    messagingSenderId: '602524351324',
    projectId: 'newsly-14f00',
    authDomain: 'newsly-14f00.firebaseapp.com',
    storageBucket: 'newsly-14f00.firebasestorage.app',
    measurementId: 'G-202J1C80Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBlU7FuP1KFGH-lGbDBflY6QlFCIKZTOA',
    appId: '1:602524351324:android:ad7aebdf3fef99656bdf99',
    messagingSenderId: '602524351324',
    projectId: 'newsly-14f00',
    storageBucket: 'newsly-14f00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_R9qd1fPNOrRHA_kdmn1B6YZsiH4iylo',
    appId: '1:602524351324:ios:d15014e1d0b0a5fb6bdf99',
    messagingSenderId: '602524351324',
    projectId: 'newsly-14f00',
    storageBucket: 'newsly-14f00.firebasestorage.app',
    iosBundleId: 'com.example.newsly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_R9qd1fPNOrRHA_kdmn1B6YZsiH4iylo',
    appId: '1:602524351324:ios:d15014e1d0b0a5fb6bdf99',
    messagingSenderId: '602524351324',
    projectId: 'newsly-14f00',
    storageBucket: 'newsly-14f00.firebasestorage.app',
    iosBundleId: 'com.example.newsly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHQViTDrXUVnJ70dTM7DlU9MVwvI2XjXE',
    appId: '1:602524351324:web:a1d27f50569644b06bdf99',
    messagingSenderId: '602524351324',
    projectId: 'newsly-14f00',
    authDomain: 'newsly-14f00.firebaseapp.com',
    storageBucket: 'newsly-14f00.firebasestorage.app',
    measurementId: 'G-6W05WLCPBG',
  );
}
